module.exports = {
  CLASS_TYPE: 'ClassDeclaration',
  METHOD_TYPE: 'MethodDefinition',
  EXPORT_TYPE: 'ExportNamedDeclaration',
  ADD_METHOD: 'ADDED_METHOD',
  REMOVE_METHOD: 'REMOVED_METHOD',
  ADD_PARAM: 'ADDED_PARAM',
  REMOVE_PARAM: 'REMOVED_PARAM',
  ADD_CLASS: 'ADDED_CLASS',
  REMOVE_CLASS: 'REMOVED_CLASS'
};